# Permalinks
permalink:           pretty

# Setup
title:               Vikram Bodicherla
tagline:             Father of 2; Android Lead for Yahoo Finance
url:                 https://www.linkedin.com/in/vikrambodicherla
paginate:            1
baseurl:             https://vikrambodicherla.github.io/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Vikram Bodicherla
  url:               https://www.linkedin.com/in/vikrambodicherla
  email:             vikram.bodicherla@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/vikrambodicherla

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Google Analytics
google_analytics: UA-15082135-3